service: all-contributors-bot
frameworkVersion: '=1.35.1'

plugins:
  - serverless-offline # must be last

custom:
  stage: ${opt:stage, self:provider.stage}
  appId:
    dev: '23544'
    prod: '23186'
  botName:
    dev: 'AllContributorsDevBot'
    prod: 'all-contributors'
  logLevel:
    dev: debug
    prod: info
  sentryDsn:
    dev: ''
    prod: 'https://e950ab524cde4682a740c218c15a461d@sentry.io/1366866'
  stageSettings:
    CacheClusterEnabled: true
    CacheClusterSize: '0.5'
    MethodSettings:
      - CachingEnabled: true
      - HttpMethod: GET
        ResourcePath: "/stats"
        CachingEnabled: true
        CacheTtlInSeconds: 3600

provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  memorySize: 512
  timeout: 30
  environment:
    BOT_NAME: ${self:custom.botName.${self:custom.stage}}
    APP_ID: ${self:custom.appId.${self:custom.stage}}
    LOG_LEVEL: ${self:custom.logLevel.${self:custom.stage}}
    SENTRY_DSN:  ${self:custom.sentryDsn.${self:custom.stage}}
    DISABLE_STATS: true
    INSTALLATION_TOKEN_TTL: 3540
    WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}
    PRIVATE_KEY: ${env:PRIVATE_KEY}

functions:
  githubWebhook:
    handler: src/serverless-webhook.handler
    events:
      - http:
          path: /
          method: post
          cors: true
  stats:
    handler: src/serverless-stats.handler
    events:
      - http:
          path: /stats
          method: get
          cors: true
