version: 2.1

docker_defaults: &docker_defaults
  docker:
    - image: circleci/node:8.10.0

commands:
  prep_env:
    description: Prepares environment with cache
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          name: Restore node_modules cache
          key: all-contributors-bot-{{ checksum "package.json"  }}-{{ checksum "yarn.lock" }}-{{ .Branch }}
  save_env_cache:
    description: Saves environment cache
    steps:
      - save_cache:
          name: Save node_modules cache
          key: all-contributors-bot-{{ checksum "package.json"  }}-{{ checksum "yarn.lock" }}-{{ .Branch }}
          paths:
            - node_modules/

jobs:
  node_modules:
    <<: *docker_defaults
    working_directory: ~/repo
    steps:
      - prep_env
      - run: yarn install --frozen-lockfile
      - save_env_cache
  test:
    <<: *docker_defaults
    working_directory: ~/repo
    steps:
      - prep_env
      - run: yarn test-ci
      - run: yarn codecov
      - store_test_results:
          path: artifacts/test-results
  lint:
    <<: *docker_defaults
    working_directory: ~/repo
    steps:
      - prep_env
      - run: yarn lint
  deploy_sandbox:
    <<: *docker_defaults
    working_directory: ~/repo
    steps:
      - prep_env
      - run: STAGE=sandbox ./.circleci/deploy.sh
  deploy_production:
    <<: *docker_defaults
    working_directory: ~/repo
    steps:
      - prep_env
      - run: yarn run semantic-release
      - run: STAGE=prod ./.circleci/deploy.sh
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - node_modules
      - test:
          requires:
            - node_modules
      - lint:
          requires:
            - node_modules
      - deploy_sandbox:
          requires:
            - test
            - lint
          filters:
            branches:
              only: master
      - verify_sandbox:
          type: approval
          requires:
            - deploy_sandbox
          filters:
            branches:
              only: master
      - deploy_production:
          requires:
            - verify_sandbox
          filters:
            branches:
              only: master


experimental:
  notify:
    branches:
      only:
        - master
